ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha!\n"
    .string "Welcome to my hideout!\p"
    .string "It shall be so until I can restore\n"
    .string "TEAM ROCKET to its former glory.\p"
    .string "But, you have found me again.\n"
    .string "So be it.\l"
    .string "This time, I'm not holding back!\p"
    .string "Once more, you shall face\n"
    .string "GIOVANNI, the greatest TRAINER!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "That was a truly intense fight.\l"
    .string "You have won!\p"
    .string "As proof, here is the EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Having lost in this fashion, \n"
    .string "I can't face my followers.\l"
    .string "I have betrayed their trust.\p"
    .string "As of today, TEAM ROCKET is\n"
    .string "finished forever!\p"
    .string "As for myself, I shall dedicate\n"
    .string "my life to training again.\p"
    .string "Let us meet again someday!\n"
    .string "Farewell!$"

ViridianCity_Gym_Text_BugsyDefeat::
    .string "Ha!\n"
    .string "That was a truly awesome fight.\l"
    .string "You've won!\p"
    .string "As proof, here is the EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "The EARTHBADGE is evidence of your\n"
	.string "skill as a POKéMON trainer. Also, take\n"
	.string "this TM.$"

ViridianCity_Gym_Text_ReceivedTM26FromBugsy::
    .string "{PLAYER} received TM26\n"
    .string "from BUGSY.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 contains BUG BITE. It's a powerful\n"
	.string "attack that can consume the berry an\n"
	.string "opponent's POKéMON is holding.$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "You do not have space for this!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "You must be running out of steam\l"
    .string "by now!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "I ran out of gas!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "You'll need power to keep up with\n"
    .string "our GYM LEADER.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "I'm working myself into a rage!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "I'm still not worthy!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON and I, we make wonderful\n"
    .string "music together!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "You are in perfect harmony!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Have you heard about our GYM LEADER,\n"
	.string "BUGSY? he's far stronger than I am.$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate is the ultimate form of\n"
    .string "martial arts!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "If my POKéMON were as good at\n"
    .string "karate as I…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "The truly talented win with style.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "I lost my grip!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "I've brought shame upon this GYM.$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "I'm the KARATE KING!\n"
    .string "Your fate rests with me!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "The POKéMON LEAGUE?\n"
    .string "You? Don't get cocky!$"

ViridianCity_Gym_Text_ColetteIntro::
    .string "Your POKéMON will cower at my might.$"

ViridianCity_Gym_Text_ColetteDefeat::
    .string "Yowch!\n"
    .string "Whiplash!$"

ViridianCity_Gym_Text_ColettePostBattle::
    .string "Wait!\n"
    .string "I was just careless!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN GYM was closed because our\n"
	.string "LEADER was out collecting BUG POKéMON.\n"
	.string "But now, he's back!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "I was beaten?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "That went faster than I expected it to.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Very impressive. BUGSY has ended many a\n"
	.string "trainer's dreams of becoming POKéMON\n"
	.string "champion.$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: BUGSY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: BUGSY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

