CliffsideCave_Text_CarlosIntro::
    .string "It's chilly down here. I hope my POKéMON\n"
	.string "don't get cold.$"

CliffsideCave_Text_CarlosDefeat::
    .string "I think they were feeling cold after all.$"

CliffsideCave_Text_CarlosPostBattle::
    .string "Be careful ahead. Those trainers are\n"
	.string "excited to battle.$"

CliffsideCave_Text_MirabelIntro::
    .string "Did you bring a pillow?$"

CliffsideCave_Text_MirabelDefeat::
    .string "I guess your POKéMON weren't sleepy$"

CliffsideCave_Text_MirabelPostBattle::
    .string "This cave is spooky. I can't shake the\n"
	.string "feeling that this whole place isn't\n"
	.string "supposed to exist.$"

CliffsideCave_Text_AdrianIntro::
    .string "Say night-night!$"

CliffsideCave_Text_AdrianDefeat::
    .string "...Not fair$"

CliffsideCave_Text_AdrianPostBattle::
    .string "I noticed that the wild POKéMON near\n"
	.string "the entrance of this cave were\n"
	.string "different from the ones down here.$"

CliffsideCave_Text_AntonioIntro::
    .string "The air is thick with tension!$"

CliffsideCave_Text_AntonioDefeat::
    .string "Oh well.$"

CliffsideCave_Text_AntonioPostBattle::
    .string "As powerful as you are, I'd be careful\n"
	.string "entering the Viridian Gym. The trainers\n"
	.string "there are experts in battle.$"

CliffsideCave_Text_MarioIntro::
    .string "My rare POKéMON will be your undoing!$"

CliffsideCave_Text_MarioDefeat::
    .string "Your team was too potent for me.$"

CliffsideCave_Text_MarioPostBattle::
    .string "Exotic POKéMON have become far more\n"
	.string "abundant across Kanto lately. I'm\n"
	.string "making a point to collect the most\l"
	.string "powerful species.$"
    
