Route6_Text_KeigoIntro::
    .string "There aren't many bugs out here.$"

Route6_Text_KeigoDefeat::
    .string "No!\n"
    .string "You're kidding!$"

Route6_Text_KeigoPostBattle::
    .string "I like bugs, so I'm going back to\n"
    .string "VIRIDIAN FOREST.$"

Route6_Text_ElijahIntro::
    .string "I've never seen you around.\n"
    .string "Are you good?$"

Route6_Text_ElijahDefeat::
    .string "You're too good!$"

Route6_Text_ElijahPostBattle::
    .string "Are my POKéMON weak?\n"
    .string "Or, am I just bad?\l"
    .string "Which do you think?$"

Route6_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"

