TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "For 3 HEART SCALES\p"
    .string "I can teach a POKéMON a move\n"
    .string "They've forgotten.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Relearn a move?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Which POKéMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Which move should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "How would you like to pay?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} handed over 99\n"
    .string "STARDUST in exchange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} handed over 3\n"
    .string "HEART SCALES in exchange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your POKéMON need to learn a\n"
    .string "move, I need 3 HEART SCALES\n"
    .string "in exchange.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "My apologies.\p" 
    .string "I can't teach an EGG\n"
    .string "any moves.$"

