LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Want me to rate the nicknames of\n"
    .string "your POKéMON?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Which POKéMON's nickname should\n"
    .string "I revise?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, is it?\p"
    .string "Would you like me to give it\n"
    .string "a new nickname?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Ah, good. Then, what shall the new\n"
    .string "nickname be?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It is a better name than before!\n"
    .string "How fortunate for you!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "I see.\n"
    .string "Do come visit again.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It looks no different from before,\n"
    .string "and yet, this is vastly superior!\p"
    .string "How fortunate for you!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a truly impeccable name!\p"
    .string "Take good care of {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Now, now.\n"
    .string "That is merely an EGG!$"

